# Generated by Django 2.2 on 2019-05-14 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipement', models.TextField(help_text='Enter a brief description of the room', max_length=1000)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular room across whole drimn', primary_key=True, serialize=False)),
                ('end_reservation', models.DateField(blank=True, null=True)),
                ('start_reservation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('i', 'In Use'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Room availability', max_length=1)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr.Room')),
            ],
            options={
                'ordering': ['end_reservation'],
            },
        ),
    ]
