# Generated by Django 2.2 on 2019-05-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstance',
            new_name='RoomInstance',
        ),
    ]
