# Generated by Django 2.2 on 2019-05-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0002_auto_20190514_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominstance',
            name='end_reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roominstance',
            name='start_reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
