# Generated by Django 2.2 on 2019-05-14 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_auto_20190514_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular User', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('indeks', models.IntegerField(null=True)),
                ('permission', models.CharField(blank=True, choices=[('b', 'Banned'), ('a', 'Allowed')], help_text='Is User allowed to create a reservation', max_length=1)),
                ('group', models.CharField(blank=True, choices=[('s', 'Student'), ('l', 'Lecturer'), ('x', 'External')], help_text='To which group does User qualify', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular Reservation', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'Accepted'), ('r', 'Rejected'), ('i', 'In Progress')], help_text='Reservation status', max_length=1)),
                ('room_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr.RoomInstance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr.Users')),
            ],
        ),
    ]
