# Generated by Django 2.2 on 2019-05-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0004_reservations_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
