# Generated by Django 2.2 on 2019-05-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0005_auto_20190514_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_instance',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dr.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_reservation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In Use'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Room availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='indeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RoomInstance',
        ),
    ]
